# You can configure this file to customize your site
globals:
    # Definition of global variable
    title : My Blog Site
    description : Yet another logecho site
    url : http://logecho.com/
blocks:
    # All blocks to compile
    post:
        source  : /posts/
        target  : /posts/
        recent  : 10
    category:
        source  :
            default : Default
        template  : archives.twig
        target    : archives.html
    tag:
        template  : archives.twig
        target    : archives.html
    archive:
        template  : archives.twig
        target    : archives.html
feeds:
    # Definition of feeds gererating
    source  : post
    recent  : 20
    target  : feeds.xml
    author  : Logecho
build:
    # The commands running after compile
    - cp -f @THEME/style.css @TARGET/style.css
sync:
    # The commands running with sync operation